version: "3.8"

services:
  container-manager:
    image: avilamatheus/api-sds:latest
    ports:
      - target: 8079
        published: 8079
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sds_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  dana:
    image: avilamatheus/dana-sds:latest
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    networks:
      - sds_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  sds_network:
    external: true
