services:
  container-manager:
    image: container-manager
    container_name: container-manager
    build:
      context: ./containermanager
    ports:
      - "8079:8079"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sds_network
  dana:
    image: avilamatheus/dana-sds
    container_name: dana
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - container-manager
    stdin_open: true
    tty: true
    networks:
      - sds_network
networks:
  sds_network:
    external: true
